image: bradrydzewski/python:2.7
env: 
  - PYTHONUNBUFFERED=1
  - DATABASE_URL=postgres://postgres@localhost/employeeapi
services:
  - postgres
script:
  - apt-get install -y socat libpq-dev python-dev
  - createdb -h localhost -U postgres employeeapi 
  - pip install -r requirements.txt
  - python manage.py test
