image: python:2.7
env: 
  - PYTHONUNBUFFERED=1
  - DATABASE_URL=postgres://postgres@localhost/employeeapi
services:
  - postgres
script:
  - apt-get update -qq
  - apt-get install -y socat libpq-dev python-dev postgresql-client-9.3 python-psycopg2
  - createdb employeeapi -E UTF8 -T template0 -h localhost -U postgres
  - pip install -r requirements.txt
  - python manage.py test
