image: python:2.7
env: 
  - PYTHONUNBUFFERED=1
  - DATABASE_URL=postgres://postgres@127.0.0.1/employeeapi
services:
  - postgres
script:
  - apt-get update -qq
  - apt-get install -y socat libpq-dev python-dev postgresql-client-9.3 python-psycopg2
  - createdb -h 127.0.0.1 -U postgres employeeapi 
  - pip install -r requirements.txt
  - python manage.py test
